-- Seed popular TEFAS funds
-- Run this after 001_setup.sql

INSERT INTO funds (code, name, category, company, currency) VALUES
('AFT', 'AK PORTFÖY AMERİKA YABANCI HİSSE SENEDİ FONU', 'Yabancı Hisse Senedi', 'AK PORTFÖY', 'TRY'),
('MAC', 'İŞ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'İŞ PORTFÖY', 'TRY'),
('TTE', 'TEB PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'TEB PORTFÖY', 'TRY'),
('IPJ', 'İŞ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'İŞ PORTFÖY', 'TRY'),
('TCD', 'TEB PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'TEB PORTFÖY', 'TRY'),
('AFA', 'AK PORTFÖY ALTIN FONU', 'Altın Fonu', 'AK PORTFÖY', 'TRY'),
('AFS', 'AK PORTFÖY HİSSE SENEDİ (TL) FONU', 'Hisse Senedi Yoğun Fon', 'AK PORTFÖY', 'TRY'),
('AFK', 'AK PORTFÖY KATILIM HİSSE SENEDİ FONU', 'Hisse Senedi Yoğun Fon', 'AK PORTFÖY', 'TRY'),
('AFP', 'AK PORTFÖY PARA PİYASASI (TL) FONU', 'Para Piyasası Fonu', 'AK PORTFÖY', 'TRY'),
('AFB', 'AK PORTFÖY BORÇLANMA ARAÇLARI FONU', 'Borçlanma Araçları Fonu', 'AK PORTFÖY', 'TRY'),
('AFH', 'AK PORTFÖY BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'AK PORTFÖY', 'TRY'),
('AFD', 'AK PORTFÖY BİRİNCİ SERBEST (DÖVİZ) ÖZEL FON', 'Serbest Fon', 'AK PORTFÖY', 'USD'),
('AFE', 'AK PORTFÖY BİRİNCİ SERBEST (TL) ÖZEL FON', 'Serbest Fon', 'AK PORTFÖY', 'TRY'),
('AFF', 'AK PORTFÖY BİRİNCİ FON SEPETİ FONU', 'Fon Sepeti Fonu', 'AK PORTFÖY', 'TRY'),
('AFG', 'AK PORTFÖY BİST 30 ENDEKSİ HİSSE SENEDİ (TL) FONU', 'Hisse Senedi Yoğun Fon', 'AK PORTFÖY', 'TRY'),
('AFI', 'AK PORTFÖY BİST 100 ENDEKSİ MODEL PORTFÖY HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU', 'Borsa Yatırım Fonu', 'AK PORTFÖY', 'TRY'),
('AFM', 'AK PORTFÖY DEĞER ODAKLI 100 ŞİRKETLERİ HİSSE SENEDİ (TL) FONU', 'Hisse Senedi Yoğun Fon', 'AK PORTFÖY', 'TRY'),
('AFO', 'AK PORTFÖY ENERJİ ŞİRKETLERİ HİSSE SENEDİ (TL) FONU', 'Hisse Senedi Yoğun Fon', 'AK PORTFÖY', 'TRY'),
('AFR', 'AK PORTFÖY EUROBOND (AMERİKAN DOLARI) BORÇLANMA ARAÇLARI FONU', 'Borçlanma Araçları Fonu', 'AK PORTFÖY', 'USD'),
('AFT2', 'AK PORTFÖY AVRUPA YABANCI HİSSE SENEDİ FONU', 'Yabancı Hisse Senedi', 'AK PORTFÖY', 'TRY'),
('AFV', 'AK PORTFÖY TEKNOLOJİ ŞİRKETLERİ HİSSE SENEDİ (TL) FONU', 'Hisse Senedi Yoğun Fon', 'AK PORTFÖY', 'TRY'),
('AFX', 'AK PORTFÖY BÜYÜYEN ŞİRKETLER HİSSE SENEDİ (TL) FONU', 'Hisse Senedi Yoğun Fon', 'AK PORTFÖY', 'TRY'),
('IFH', 'İŞ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'İŞ PORTFÖY', 'TRY'),
('IFS', 'İŞ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'İŞ PORTFÖY', 'TRY'),
('IFD', 'İŞ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST (DÖVİZ) FON', 'Serbest Fon', 'İŞ PORTFÖY', 'USD'),
('IFP', 'İŞ PORTFÖY YÖNETİMİ A.Ş. PARA PİYASASI (TL) FONU', 'Para Piyasası Fonu', 'İŞ PORTFÖY', 'TRY'),
('IFA', 'İŞ PORTFÖY YÖNETİMİ A.Ş. ALTIN FONU', 'Altın Fonu', 'İŞ PORTFÖY', 'TRY'),
('IFK', 'İŞ PORTFÖY YÖNETİMİ A.Ş. KATILIM HİSSE SENEDİ FONU', 'Hisse Senedi Yoğun Fon', 'İŞ PORTFÖY', 'TRY'),
('IFI', 'İŞ PORTFÖY YÖNETİMİ A.Ş. BİST 30 ENDEKSİ HİSSE SENEDİ (TL) FONU', 'Hisse Senedi Yoğun Fon', 'İŞ PORTFÖY', 'TRY'),
('IFB', 'İŞ PORTFÖY YÖNETİMİ A.Ş. BORÇLANMA ARAÇLARI FONU', 'Borçlanma Araçları Fonu', 'İŞ PORTFÖY', 'TRY'),
('TFS', 'TEB PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'TEB PORTFÖY', 'TRY'),
('TFH', 'TEB PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'TEB PORTFÖY', 'TRY'),
('TFP', 'TEB PORTFÖY YÖNETİMİ A.Ş. PARA PİYASASI (TL) FONU', 'Para Piyasası Fonu', 'TEB PORTFÖY', 'TRY'),
('TFA', 'TEB PORTFÖY YÖNETİMİ A.Ş. ALTIN FONU', 'Altın Fonu', 'TEB PORTFÖY', 'TRY'),
('TFK', 'TEB PORTFÖY YÖNETİMİ A.Ş. KATILIM HİSSE SENEDİ FONU', 'Hisse Senedi Yoğun Fon', 'TEB PORTFÖY', 'TRY'),
('GFS', 'GARANTİ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'GARANTİ PORTFÖY', 'TRY'),
('GFH', 'GARANTİ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'GARANTİ PORTFÖY', 'TRY'),
('GFP', 'GARANTİ PORTFÖY YÖNETİMİ A.Ş. PARA PİYASASI (TL) FONU', 'Para Piyasası Fonu', 'GARANTİ PORTFÖY', 'TRY'),
('GFA', 'GARANTİ PORTFÖY YÖNETİMİ A.Ş. ALTIN FONU', 'Altın Fonu', 'GARANTİ PORTFÖY', 'TRY'),
('YFS', 'YAPI KREDİ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'YAPI KREDİ PORTFÖY', 'TRY'),
('YFH', 'YAPI KREDİ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'YAPI KREDİ PORTFÖY', 'TRY'),
('YFP', 'YAPI KREDİ PORTFÖY YÖNETİMİ A.Ş. PARA PİYASASI (TL) FONU', 'Para Piyasası Fonu', 'YAPI KREDİ PORTFÖY', 'TRY'),
('VFS', 'VAKIF PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'VAKIF PORTFÖY', 'TRY'),
('VFH', 'VAKIF PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'VAKIF PORTFÖY', 'TRY'),
('VFP', 'VAKIF PORTFÖY YÖNETİMİ A.Ş. PARA PİYASASI (TL) FONU', 'Para Piyasası Fonu', 'VAKIF PORTFÖY', 'TRY'),
('HFS', 'HALKBANK PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'HALKBANK PORTFÖY', 'TRY'),
('HFH', 'HALKBANK PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'HALKBANK PORTFÖY', 'TRY'),
('ZFS', 'ZİRAAT PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'ZİRAAT PORTFÖY', 'TRY'),
('ZFH', 'ZİRAAT PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'ZİRAAT PORTFÖY', 'TRY'),
('QFS', 'QNB FİNANS PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'QNB FİNANS PORTFÖY', 'TRY'),
('QFH', 'QNB FİNANS PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'QNB FİNANS PORTFÖY', 'TRY'),
('DFS', 'DENİZ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'DENİZ PORTFÖY', 'TRY'),
('DFH', 'DENİZ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'DENİZ PORTFÖY', 'TRY'),
('NFS', 'NUROL PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'NUROL PORTFÖY', 'TRY'),
('NFH', 'NUROL PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'NUROL PORTFÖY', 'TRY'),
('MFS', 'METLİFE PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'METLİFE PORTFÖY', 'TRY'),
('MFH', 'METLİFE PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'METLİFE PORTFÖY', 'TRY'),
('EFS', 'ERGO PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'ERGO PORTFÖY', 'TRY'),
('EFH', 'ERGO PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'ERGO PORTFÖY', 'TRY'),
('AFS2', 'ACTUS PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'ACTUS PORTFÖY', 'TRY'),
('AFH2', 'ACTUS PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'ACTUS PORTFÖY', 'TRY'),
('BFS', 'BECO PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'BECO PORTFÖY', 'TRY'),
('BFH', 'BECO PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'BECO PORTFÖY', 'TRY'),
('KFS', 'KİRAÇ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'KİRAÇ PORTFÖY', 'TRY'),
('KFH', 'KİRAÇ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'KİRAÇ PORTFÖY', 'TRY'),
('LFS', 'LEADER PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'LEADER PORTFÖY', 'TRY'),
('LFH', 'LEADER PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'LEADER PORTFÖY', 'TRY'),
('PFS', 'PİRAYA PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'PİRAYA PORTFÖY', 'TRY'),
('PFH', 'PİRAYA PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'PİRAYA PORTFÖY', 'TRY'),
('RFS', 'RABOBANK PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'RABOBANK PORTFÖY', 'TRY'),
('RFH', 'RABOBANK PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'RABOBANK PORTFÖY', 'TRY'),
('SFS', 'SARAT PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'SARAT PORTFÖY', 'TRY'),
('SFH', 'SARAT PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'SARAT PORTFÖY', 'TRY'),
('TFS2', 'TRIUMPH PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'TRIUMPH PORTFÖY', 'TRY'),
('TFH2', 'TRIUMPH PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'TRIUMPH PORTFÖY', 'TRY'),
('UFS', 'UNİCORNER PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'UNİCORNER PORTFÖY', 'TRY'),
('UFH', 'UNİCORNER PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'UNİCORNER PORTFÖY', 'TRY'),
('WFS', 'WELT PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ SERBEST FON', 'Serbest Fon', 'WELT PORTFÖY', 'TRY'),
('WFH', 'WELT PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ HİSSE SENEDİ SERBEST FON', 'Hisse Senedi Yoğun Fon', 'WELT PORTFÖY', 'TRY')
ON CONFLICT (code) DO NOTHING;
